# Generated by Django 4.1.3 on 2022-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_environment", "0007_lesson_start_lesson_wrapup"),
    ]

    operations = [
        migrations.RemoveField(model_name="learnerstatus", name="current_lesson",),
        migrations.AddField(
            model_name="learnerstatus",
            name="score",
            field=models.IntegerField(default=5),
        ),
    ]
